BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
EXECUTE sp_rename N'dbo.FORMULA_DETAIL.BYPASS_CRUSHER', N'Tmp_CRUSHER', 'COLUMN' 
GO
EXECUTE sp_rename N'dbo.FORMULA_DETAIL.Tmp_CRUSHER', N'CRUSHER', 'COLUMN' 
GO
ALTER TABLE dbo.FORMULA_DETAIL SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
