CREATE UNIQUE NONCLUSTERED INDEX [UX_FORMULA_MASTER_FORMULA_CODE_LINE_NO] ON [dbo].[FORMULA_MASTER]
(
	[FORMULA_CODE] ASC,
	[LINE_NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = OFF, ALLOW_PAGE_LOCKS = OFF) ON [PRIMARY]
GO


