USE [bcs_development]
GO

/****** Object:  Table [dbo].[SCALE_MASTER]    Script Date: 06/12/2012 22:10:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SCALE_MASTER](
	[SCALE_ID] [int] IDENTITY(1,1) NOT NULL,
	[SCALE_NAME] [varchar](16) NOT NULL,
 CONSTRAINT [PK_SCALE_MASTER] PRIMARY KEY CLUSTERED 
(
	[SCALE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

