USE [bcs_development]
GO

/****** Object:  Table [dbo].[BIN_MASTER]    Script Date: 06/12/2012 22:11:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[BIN_MASTER](
	[BIN_ID] [int] IDENTITY(1,1) NOT NULL,
	[BIN_NAME] [varchar](8) NOT NULL,
 CONSTRAINT [PK_BIN_MASTER] PRIMARY KEY CLUSTERED 
(
	[BIN_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

