USE [bcs_development]
GO

/****** Object:  Table [dbo].[RM_MASTER]    Script Date: 06/12/2012 22:11:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[RM_MASTER](
	[RM_ID] [int] IDENTITY(1,1) NOT NULL,
	[RM_CODE] [varchar](32) NOT NULL,
	[SCALE_ID] [int] NOT NULL,
 CONSTRAINT [PK_RM_MASTER] PRIMARY KEY CLUSTERED 
(
	[RM_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[RM_MASTER]  WITH CHECK ADD  CONSTRAINT [FK_RM_MASTER_SCALE_MASTER] FOREIGN KEY([SCALE_ID])
REFERENCES [dbo].[SCALE_MASTER] ([SCALE_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[RM_MASTER] CHECK CONSTRAINT [FK_RM_MASTER_SCALE_MASTER]
GO

