USE [bcs_development]
GO

/****** Object:  Table [dbo].[LINE_MASTER]    Script Date: 06/12/2012 22:13:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[LINE_MASTER](
	[LINE_NO] [int] IDENTITY(1,1) NOT NULL,
	[LINE_CODE] [varchar](8) NOT NULL,
 CONSTRAINT [PK_LINE_MASTER] PRIMARY KEY CLUSTERED 
(
	[LINE_NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

