USE [bcs_development]
GO

/****** Object:  Table [dbo].[FORMULA_MASTER]    Script Date: 06/12/2012 22:14:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FORMULA_MASTER](
	[FORMULA_ID] [int] IDENTITY(1,1) NOT NULL,
	[FORMULA_NAME] [varchar](32) NOT NULL,
	[LINE_NO] [int] NOT NULL,
 CONSTRAINT [PK_FORMULA_MASTER] PRIMARY KEY CLUSTERED 
(
	[FORMULA_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[FORMULA_MASTER]  WITH CHECK ADD  CONSTRAINT [FK_FORMULA_MASTER_LINE_MASTER] FOREIGN KEY([LINE_NO])
REFERENCES [dbo].[LINE_MASTER] ([LINE_NO])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[FORMULA_MASTER] CHECK CONSTRAINT [FK_FORMULA_MASTER_LINE_MASTER]
GO

