USE [bcs_development]
GO

/****** Object:  Table [dbo].[FORMULA_DETAIL]    Script Date: 06/12/2012 22:14:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FORMULA_DETAIL](
	[FORMULA_ID] [int] NOT NULL,
	[MATERIAL_ID] [int] NOT NULL,
	[FINAL_ACTUAL_VALUE] [numeric](10, 2) NOT NULL,
 CONSTRAINT [PK_FORMULA_DETAIL] PRIMARY KEY CLUSTERED 
(
	[FORMULA_ID] ASC,
	[MATERIAL_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[FORMULA_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_FORMULA_DETAIL_FORMULA_MASTER] FOREIGN KEY([FORMULA_ID])
REFERENCES [dbo].[FORMULA_MASTER] ([FORMULA_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[FORMULA_DETAIL] CHECK CONSTRAINT [FK_FORMULA_DETAIL_FORMULA_MASTER]
GO

ALTER TABLE [dbo].[FORMULA_DETAIL]  WITH CHECK ADD  CONSTRAINT [FK_FORMULA_DETAIL_MATERIAL_MASTER] FOREIGN KEY([MATERIAL_ID])
REFERENCES [dbo].[MATERIAL_MASTER] ([MATERIAL_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[FORMULA_DETAIL] CHECK CONSTRAINT [FK_FORMULA_DETAIL_MATERIAL_MASTER]
GO

