USE [bcs_development]
GO

/****** Object:  Table [dbo].[SHIFT_MASTER]    Script Date: 06/12/2012 22:15:11 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SHIFT_MASTER](
	[SHIFT_CODE] [int] NOT NULL,
	[SHIFT_NAME] [varchar](32) NOT NULL,
 CONSTRAINT [PK_SHIFT_MASTER] PRIMARY KEY CLUSTERED 
(
	[SHIFT_CODE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

